behavior:
  ros__parameters:
    frequency: 20.0 # {double} [Hz]
    plan_frequency: 0.5 # {double} [Hz]

map_server:
  ros__parameters:
    max_cost: 99 # {int8_t}
    circumscribed_radius: 0.15 # {double} [m]
    inflation_radius: 0.8 # {double} [m]
    cost_exponent: 0.2 # {double}

planner:
  ros__parameters:
    xy_tolerance: 0.1   # meters
    yaw_tolerance: 0.1  # radians
    doorway_tolerance: 6 # {int} [per unit]

controller:
  ros__parameters:
    frequency: 20.0 # {double} [Hz]
    lookahead_distance: 0.5 # {double} [m]
    stop_thres: 0.15 # {double} [m]
    lookahead_lin_vel: 2.0 # {double} [m/s]
    max_lin_acc: 6.0 # {double} [m/s^2]
    max_lin_vel: 3.0  # {double} [m/s]
    max_ang_acc: 6.0 # {double} [rad/s^2]
    max_ang_vel: 3.0 # {double} [rad/s]

